
name: Deploy React App to GitHub Pages

on:
  push:
    branches: [ main ]  # Remplacez par "master" si c'est votre branche principale

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # Utilisez la version de Node.js appropriée pour votre projet
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build project
        run: npm run build
        env:
          REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL }}  # Si vous avez des variables d'environnement
          
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build  # Le dossier qui contient les fichiers à déployer
          branch: gh-pages  # La branche où les fichiers seront déployés
          token: ${{ secrets.GITHUB_TOKEN }}  # Token fourni automatiquement par GitHub
